service: default
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: /static
  static_dir: static

- url: .*
  script: src.handler.app

libraries:
- name: MySQLdb
  version: "1.2.5"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^docs$
- ^elem$
