service: default
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: .*
  script: src.handler.app

- url: /static
  static_dir: static

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

libraries:
- name: MySQLdb
  version: "1.2.5"
