service: default
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

#- url: /.*
#  script: src.handlers.api.v2.app
